export class Mensajes {
    public MSJ_SUCCES: string = 'success';
    public MSJ_ERROR: string = 'error';
    public MSJ_WARNING: string = 'warning';
    public MSJ_DELETE: string = 'delete';
    public MSJ_ACEPTAR: string = 'Aceptar';
    public MSJ_PROCESANDO: string = 'Procesando...';
    public MSJ_SELECCIONAR: string = 'Seleccionar';
    public MSJ_INGRESAR: string = 'Ingresar';
    public MSJ_TODAS: string = 'TODAS';
    public MSJ_CAMPO_OBLIGATORIO: string = 'Campo obligatorio';
    public MSJ_SIN_UBICACIONES: string = 'No se encontraron ubicaciones de la OOAD seleccionada';
    public MSJ_SIN_UM: string = 'No se encontraron Unidades Médicas de la OOAD seleccionada';
    public MSJ_SELECT_XML: string = 'Selecciona el archivo XML y cárgalo al sistema de espirometrías';

    public MSJ_BUSCANDO: string = 'Buscando...';
    public MSJ_GET_CATALOGO: string = 'Cargando catálogo';


    public TITULO_GESTION_ESPIROMETRIA: string = 'Gestión de Equipo de Espirometría';
    public TITULO_REPORTES: string = 'Consultar Reporte';
    public TITULO_VER_REPORTES: string = 'Visualizar reporte';
    public TITULO_CARGA_XML: string = 'Cargar Archivo XML';
    public TITULO_EDITAR_ESPIROMETRO: string = 'Editar Equipo de Espirometría';
    public TITULO_ALTA_ESPIROMETRO: string = 'Alta de Equipo de Espirometría';
    public TITULO_ALERT_EDITAR_ESPIROMETRO: string = 'Edición de espirómetro';
    public TITULO_ALERT_ALTA_EXITOSA: string = 'Alta exitosa';
    public TITULO_ALERT_DESACTIVAR: string = 'Desactivación';
    public TITULO_ALERT_ACTIVAR: string = 'Activación';
    public TITULO_ALERT_ERROR: string = 'Error en la ejecución';

    public MSG001: string = 'El nombre del archivo es incorrecto. Favor de verificar';
    public MSG002: string = 'Usuario o contraseña incorrecto';
    public MSG002_1: string = 'Usuario o contraseña incorrectos. Favor de verificar.';
    public total_registros_almacenados: string = '';
    public total_registros_enviados: string = '';
    public MSG003: string = 'R_A de R_E  registros fueron almacenados de forma exitosa';
    public MSG004: string = 'Algunos de los datos ingresados es incorrecto. Favor de verificar.';
    public MSG005: string = 'Existen registros cuyo NSS o número de matrícula son incorrectos, o bien, no cuentan con pruebas realizadas';
    public MSG005_1:string= '¿Desea continuar con el almacenamiento de los registros correctos?';
    public MSG006: string = 'Archivo XML incorrecto, favor de verificar.';
    public MSG007: string = '¿Está seguro de que desea salir?';
    public MSG008: string = 'No se encontraron registros nuevos.';
    public MSG009: string = 'No cuentas con perfil de Administrador.';
    public MSG010: string = 'Seleccione un parámetro de búsqueda';
    public MSG011: string = 'NSS no válido. Favor de verificar.';
    public MSG012: string = 'No se encontraron registros relacionados a los criterios de búsqueda ingresados, favor de validar.';
    public MSG013: string = '¿Seguro que deseas desactivar este equipo de espirometría?';
    public MSG013_1: string = '¿Seguro que deseas activar este equipo de espirometría?';
    public MSG014: string = 'Eliminación. El equipo de espirometría se eliminó correctamente.';
    public MSG014_1: string = 'El equipo de espirometría se desactivó correctamente.';
    public MSG014_2: string = 'El equipo de espirometría se activó correctamente.';
    public MSG015: string = 'El número de serie es incorrecto. Favor de verificar.';
    public MSG016: string = 'Favor de comunicarse con el administrador del Sistema Integral de Salud en el Trabajo (SIST) para verificar su nombre de usuario y contraseña.';
    public MSG017: string = 'Algunos de los registros nuevos no cuentan con archivo PDF.';
    public MSG018: string = 'El archivo se guardó correctamente.';
    public MSG019: string = 'Error en la descarga del documento. Intenta nuevamente.';
    public MSG020: string = 'Error al guardar la información. Intenta nuevamente.';
    public MSG021: string = 'Error al cargar el archivo. Intenta nuevamente.';
    public MSG022: string = 'El archivo no se encuentra disponible. Intenta más tarde.';
    public MSG023: string = 'El espirómetro se dio de alta exitosamente.';
    public MSG024: string = '¿Seguro que deseas editar este equipo de espirometría?';
    public MSG025: string = 'El NSS no es correcto.';
    public MSG026: string = 'El número de matrícula no es correcto.';
    public MSG027: string = 'El registro no cuenta con el resultado de la prueba realizada.';
    public MSG028: string = '¿Está seguro de imprimir el archivo?';
    public MSG029: string = 'No cuentas con el perfil de médico.';
    public MSG030: string = 'El espirómetro fue editado correctamente.';
}
